apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    run: mysql
spec:
  selector:
    app: mysql
  type: NodePort
  ports:
    - port: 3306
      targetPort: 3306
      nodePort: 30036
      protocol: TCP
